language: android
sudo: required
android:
  components:
    - platform-tools
    - tools
    - android-23
    - build-tools-25.0.3
    - extra-android-m2repository
    - extra-android-support

before_install:
  - mkdir "$ANDROID_HOME/licenses"
  - echo "d56f5187479451eabf01fb78af6dfcb131a6481e" > "$ANDROID_HOME/licenses/android-sdk-license"
  
before_script: chmod a+x gradlew
script: ./gradlew clean build
