language: android
sudo: required
android:
  components:
    - platform-tools
    - tools
    - android-23
    - build-tools-25.0.3
    - extra-android-m2repository
    - extra-android-support
    
  licenses:
    - 'android-sdk-preview-license-52d11cd2'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'
before_script: chmod a+x gradlew
script: ./gradlew clean build
